### ISSUE TITLE
Produce Nix bundle (alternative to static binaries)

### ISSUE THREAD

**Issue by srid** [srid/neuron#260]
Proof of concept by [luchs on lobste.rs](https://lobste.rs/s/xufl8d/foam_personal_knowledge_management#c_qexngl): 
* https://builds.sr.ht/~luchs/job/244254

As an alternative to #183, build a [nix-bundle](https://github.com/matthewbauer/nix-bundle) for neuron in CI and upload the resulting binary.

![image](https://user-images.githubusercontent.com/3998/86136543-355a1180-baba-11ea-8194-f7d004e487a6.png)

There is an initial delay (for unpacking), but otherwise it works with these known issues:

* Breaks on relative paths in command-line

## tasks

* [x] Automate nix-bundle creation in CI
* [ ] ~~Upload artifacts somewhere (latest should always be available at a known URL)~~
  * https://github.com/actions/download-artifact/issues/3
* [x] Test the binary by using it in one of [neuron-template](https://github.com/srid/neuron-template)'s sites' CI
* [x] Use the binary in neuron-template CI
* [x] Documentation
* [ ] macOS?

```
./nix-bundle.sh '(let neuronSrc = builtins.fetchTarball https://github.com/srid/neuron/archive/master.tar.gz; in import neuronSrc)' /bin/neuron
```

**Comment by srid** [comment]
macOS is unsupported: https://github.com/matthewbauer/nix-bundle/issues/17

At least we can hope to produce a Linux executable for https://github.com/srid/neuron-template

**Comment by srid** [comment]
Linux bundle will now be built in CI. https://github.com/srid/neuron/runs/824453116

![image](https://user-images.githubusercontent.com/3998/86185401-52b3cd80-bb04-11ea-8b5d-b6a43752368e.png)

**Comment by shyba** [comment]
Thank you! I can confirm it works if that helps.

**Comment by anka-213** [comment]
I did manage to make it work on CI: https://github.com/anka-213/test-gh-actions-neuron/blob/6aa7a4756f0b0de4b73f819393a65a4af50a2933/.github/workflows/ci.yaml#L27-L31

https://github.com/anka-213/test-gh-actions-neuron/actions/runs/161777244

On a side note, I tried the same github-pages deploy script as you used (because I had trouble with relative paths as you mentioned above and thought it was deployment that failed) and it was notably slower to download. Reverting shaved off another 13 seconds, so now it builds in just 25 seconds, with a total CI time of . 🎉 

On another side note: It seems like your "publish neuron site" script is [building neuron from source](https://github.com/srid/neuron/runs/843129343?check_suite_focus=true) instead of downloading it. Probably because it runs in parallel with the "CI" action, so it hasn't been uploaded yet.

**Comment by srid** [comment]
@anka-213 Awesome, I confirm that it works for me! https://github.com/srid/alien-psychology/commit/12bf547809ff219b339e9ded668e893c5153cb23

I'll switch [neuron-template](https://github.com/srid/neuron-template) to this (as well to the peaceiris/actions-gh-pages action, which runs quicker in addition to automatically deleting stale files). It seems that CI can use the `GITHUB_TOKEN` secret ([see here](https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token)), that is required to download the artifact, as long as the committer has write access to the repo.

I was originally thinking about having the CI upload the bundle to some location, but your solution is obviously simpler and involves less maintenance.
