### ISSUE TITLE
Include all of YAML frontmatter in JSON

### ISSUE THREAD

**Issue by srid** [srid/neuron#570]
`neuron query`'s JSON output should include everything in a Markdown file's YAML frontmatter as-is. This will 

1. automatically include for example "tags" (regardless of tags plugin being enabled), thus enabling editors (@felko, @chiefnoah) to directly read the tags from frontmatter without having to parse the internal plugin data. They can access also other custom metadata even if neuron doesn't know anything about them. 
2. facilitate use of tags by dirtree plugin without depending on the tag query plugin (see #569)\

**tasks**

- [x] Expose YAML frontmatter in `neuron query` (#571)
- [x] Have the tags plugin (and dirtree) store their tags in the same metadata 
- [x] Sanity check final JSON
    - Consider removing `PluginData` field (save bandwidth; less spam-y output)
    - Remove `Content` field (which is always null); and other null fields automatically
    - Remove `TitleInBody`
- [x] Nudge vim/emacs extensions to switch over to using metadata, instead of internal plugin data

**Comment by srid** [comment]
Done: https://github.com/srid/neuron/pull/572
